exports.insuranceDataSet = {
    '신준수': { insurance: '삼성화재 애니펫' },
    '김철수': { insurance: '삼성화재 애니펫' },
    '박보검': { insurance: '삼성화재 애니펫' },
    '김미영': { insurance: 'DB손해보험 아이러브펫보험' },
    '홍길동': { insurance: 'DB손해보험 프로미 반려동물 보험' },
    '김밥밥': { insurance: 'KB손해보험 KB펫코노미' },
    '뿌링클': { insurance: 'DB손해보험 프로미 반려동물 보험' },
    '김치치': { insurance: 'DB손해보험 프로미 반려동물 보험' },
    '김소미': { insurance: 'DB손해보험 아이러브펫보험' },
    '김소영': { insurance: 'DB손해보험 아이러브펫보험' },
    '신준식': { insurance: '삼성화재 애니펫' },
    '신준일': { insurance: '삼성화재 애니펫' },
    '신준이': { insurance: '삼성화재 애니펫' },
    '신준삼': { insurance: '삼성화재 애니펫' },
    '김소일': { insurance: 'NH 농협손해본험 반려동물장제비보험' },
    '김소이': { insurance: 'NH 농협손해본험 반려동물장제비보험' },
    '김소삼': { insurance: 'NH 농협손해본험 반려동물장제비보험' },
    '김소사': { insurance: 'NH 농협손해본험 반려동물장제비보험' },
    '김소오': { insurance: 'NH 농협손해본험 반려동물장제비보험' }
};